[project]
name = "egd_site"
authors = [
    { name = "Ayuda Efectiva" }
]
description = "EGD Site"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"
